var Pesho = new Player('Pesho');
var Gosho = new Player('Gosho');
var smallSword = new Weapon(2, 5);
var bigSword = new Weapon(2, 10);
Pesho.addToInventory(bigSword);
Pesho.addToInventory(new HealthPotion());
Pesho.addToInventory(new ManaPotion());
Gosho.addToInventory(smallSword);
Gosho.addToInventory(new HealthPotion());
Pesho.showInventory();
Gosho.showInventory();
Pesho.hit(Gosho);
Pesho.usePotion('health');
console.log('Pesho health: ', Pesho.getHealth());
Gosho.hit(Pesho);
Gosho.hit(Pesho);
console.log('Pesho mana: ', Pesho.getMana());
Pesho.usePotion('mana');
console.log('Pesho mana: ', Pesho.getMana());
Gosho.usePotion('mana');
Gosho.hit(Pesho);
Gosho.hit(Pesho);